name: Reusable Nix flake update (public repos)

on:
  workflow_call:

jobs:
  install-nix:
    permissions:
      pull-requests: write
      contents: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Install & configure Nix for public Hackworth Ltd repos.
        uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hackworthltd.cachix.org-1:0JTCI0qDo2J+tonOalrSQP3yRNleN6bQucJ05yDltRI= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk=
            substituters = https://cache.nixos.org?priority=10 https://hackworthltd.cachix.org?priority=30 https://hydra.iohk.io?priority=50 https://cache.zw3rk.com?priority=60

      - name: Check out repo
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Enable Sigstore GitHub Action signing.
        uses: chainguard-dev/actions/setup-gitsign@main

      - name: Update Nix dependencies.
        uses: DeterminateSystems/update-flake-lock@v16
        with:
          commit-msg: "chore(nix): Update dependencies."
          branch: "chore/update-nix-dependencies"
          pr-title: "chore(nix): Update dependencies."
          pr-labels: |
            automated
            dependencies
